version: '3'
services:
  redis-stack:
    image: redis:latest
    container_name: redis-stack
    hostname: redis-stack
    ports:
      - '6379:6379'
    healthcheck:
      test: redis-cli ping | grep -q '^PONG' || exit 1
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    hostname: redis-insight
    ports:
      - '8001:8001'